LANG=${LANG:-"C.UTF-8"}
LANGUAGE=${LANGUAGE:-"C.UTF-8"}
LC_ALL=${LC_ALL:-"C.UTF-8"}
PUBLIC_PASSWD=${PUBLIC_PASSWD:-"ftp"}
PRIVATE_USERNAME=${PRIVATE_USERNAME:-"lug"}
PRIVATE_PASSWD=${PRIVATE_PASSWD:-"password"}
PASV_ADDRESS=${PASV_ADDRESS:-"127.0.0.1"}
